export * from './administracin-analtica.service';
import { AdministracinAnalticaService } from './administracin-analtica.service';
export * from './administracin-auditora.service';
import { AdministracinAuditoraService } from './administracin-auditora.service';
export * from './administracin-categoras.service';
import { AdministracinCategorasService } from './administracin-categoras.service';
export * from './administracin-configuracin.service';
import { AdministracinConfiguracinService } from './administracin-configuracin.service';
export * from './administracin-imgenes.service';
import { AdministracinImgenesService } from './administracin-imgenes.service';
export * from './administracin-productos.service';
import { AdministracinProductosService } from './administracin-productos.service';
export * from './administracin-roles-y-permisos.service';
import { AdministracinRolesYPermisosService } from './administracin-roles-y-permisos.service';
export * from './administracin-usuarios.service';
import { AdministracinUsuariosService } from './administracin-usuarios.service';
export * from './autenticacin.service';
import { AutenticacinService } from './autenticacin.service';
export * from './catlogo-pblico.service';
import { CatlogoPblicoService } from './catlogo-pblico.service';
export * from './medios.service';
import { MediosService } from './medios.service';
export const APIS = [AdministracinAnalticaService, AdministracinAuditoraService, AdministracinCategorasService, AdministracinConfiguracinService, AdministracinImgenesService, AdministracinProductosService, AdministracinRolesYPermisosService, AdministracinUsuariosService, AutenticacinService, CatlogoPblicoService, MediosService];
