/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeCount } from './type-count';


export interface AnalyticsSummaryResponse { 
    from?: string;
    to?: string;
    /**
     * Siempre incluye los 4 tipos, con count 0 si no tuvieron eventos.
     */
    byType?: Array<TypeCount>;
    totalEvents?: number;
}

