/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssignRoleRequest { 
    /**
     * Falla si el rol otorga un permiso que quien asigna no tiene.
     */
    roleId: string;
}

