/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLogResponse { 
    id?: string;
    action?: AuditLogResponseActionEnum;
    entityType?: AuditLogResponseEntityTypeEnum;
    entityId?: string;
    /**
     * Quién hizo el cambio.
     */
    userId?: string;
    /**
     * Snapshot previo a la escritura. null en CREATE.
     */
    before?: { [key: string]: any | null; } | null;
    /**
     * Snapshot posterior a la escritura. null en DELETE.
     */
    after?: { [key: string]: any | null; } | null;
    /**
     * IP de quien hizo el cambio, nunca en claro.
     */
    ipHash?: string;
    at?: string;
}
export enum AuditLogResponseActionEnum {
    Create = 'CREATE',
    Update = 'UPDATE',
    Delete = 'DELETE'
};
export enum AuditLogResponseEntityTypeEnum {
    Product = 'PRODUCT',
    Category = 'CATEGORY',
    AppUser = 'APP_USER',
    Role = 'ROLE'
};



