/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscountResponse { 
    type?: DiscountResponseTypeEnum;
    value?: number;
    startsAt?: string | null;
    endsAt?: string | null;
}
export enum DiscountResponseTypeEnum {
    Percentage = 'PERCENTAGE',
    FixedAmount = 'FIXED_AMOUNT'
};



