/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscountRequest { 
    type: DiscountRequestTypeEnum;
    /**
     * Porcentaje (0.01-90) o monto fijo menor que el precio, según `type`.
     */
    value: number;
    /**
     * Si es futuro, el precio efectivo sigue siendo el de lista hasta entonces.
     */
    startsAt?: string | null;
    /**
     * Si ya pasó, el precio efectivo vuelve a ser el de lista.
     */
    endsAt?: string | null;
}
export enum DiscountRequestTypeEnum {
    Percentage = 'PERCENTAGE',
    FixedAmount = 'FIXED_AMOUNT'
};



