/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FieldViolation { 
    /**
     * Campo del cuerpo de la petición que falló.
     */
    field?: string;
    /**
     * Motivo del rechazo.
     */
    message?: string;
}

