/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageUploadResponse { 
    id?: string;
    /**
     * PROCESSING justo después de subir; cambia cuando termina el procesamiento en segundo plano.
     */
    status?: ImageUploadResponseStatusEnum;
}
export enum ImageUploadResponseStatusEnum {
    Processing = 'PROCESSING',
    Ready = 'READY',
    Failed = 'FAILED'
};



