/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RenditionRef } from './rendition-ref';


export interface ImageRef { 
    altText?: string;
    card?: RenditionRef;
    /**
     * Versión a doble densidad de píxeles, para pantallas retina.
     */
    card2x?: RenditionRef;
    thumb?: RenditionRef;
}

