/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RenditionRef } from './rendition-ref';


export interface ImageDetailRef { 
    altText?: string;
    detail?: RenditionRef;
}

