/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    /**
     * JWT de acceso, válido 15 minutos. Va en `Authorization: Bearer`.
     */
    accessToken?: string;
    accessTokenExpiresAt?: string;
    userId?: string;
    email?: string;
    fullName?: string;
    /**
     * Códigos de permiso efectivos del usuario.
     */
    permissions?: Set<string>;
    mustChangePassword?: boolean;
}

