/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MeResponse { 
    id?: string;
    email?: string;
    fullName?: string;
    /**
     * Códigos de permiso efectivos del usuario.
     */
    permissions?: Set<string>;
    mustChangePassword?: boolean;
}

