/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldViolation } from './field-violation';


/**
 * Error en formato RFC 9457 application/problem+json.
 */
export interface ProblemDetail { 
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    /**
     * Identificador de correlación con los logs del servidor.
     */
    traceId?: string;
    /**
     * Presente solo en errores de validación (400).
     */
    errors?: Array<FieldViolation> | null;
}

