/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductUpdateRequest { 
    sku: string;
    name: string;
    shortDescription?: string;
    /**
     * HTML; se sanea con lista blanca al guardar.
     */
    description?: string;
    usageInstructions?: string;
    categoryId: string;
    price: number;
    stock?: number;
    /**
     * Si es false, el producto se trata como siempre disponible.
     */
    trackStock?: boolean;
    featured?: boolean;
    /**
     * Orden manual dentro de su categoría.
     */
    sortOrder?: number;
}

