/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageRef } from './image-ref';
import { CategoryRef } from './category-ref';


export interface ProductCard { 
    id?: string;
    sku?: string;
    name?: string;
    slug?: string;
    shortDescription?: string;
    price?: number;
    effectivePrice?: number;
    onSale?: boolean;
    discountPercentage?: number;
    currency?: string;
    inStock?: boolean;
    category?: CategoryRef;
    primaryImage?: ImageRef;
}

