/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryRef } from './category-ref';
import { DiscountResponse } from './discount-response';


export interface ProductAdminResponse { 
    id?: string;
    sku?: string;
    name?: string;
    slug?: string;
    shortDescription?: string;
    /**
     * HTML saneado con lista blanca (CLAUDE.md).
     */
    description?: string;
    usageInstructions?: string;
    categoryId?: string;
    category?: CategoryRef;
    /**
     * Precio de lista.
     */
    price?: number;
    /**
     * Precio tras aplicar el descuento vigente, si lo hay.
     */
    effectivePrice?: number;
    onSale?: boolean;
    discountPercentage?: number;
    currency?: string;
    stock?: number;
    /**
     * Si es false, el producto se trata como siempre disponible.
     */
    trackStock?: boolean;
    inStock?: boolean;
    status?: ProductAdminResponseStatusEnum;
    publishedAt?: string | null;
    featured?: boolean;
    /**
     * Orden manual dentro de su categoría.
     */
    sortOrder?: number;
    discount?: DiscountResponse;
    createdAt?: string;
    updatedAt?: string;
}
export enum ProductAdminResponseStatusEnum {
    Draft = 'DRAFT',
    Published = 'PUBLISHED',
    Archived = 'ARCHIVED'
};



