/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageRef } from './image-ref';
import { CategoryRef } from './category-ref';


export interface ProductCard { 
    id?: string;
    sku?: string;
    name?: string;
    slug?: string;
    shortDescription?: string;
    /**
     * Precio de lista.
     */
    price?: number;
    /**
     * Precio tras aplicar el descuento vigente, si lo hay.
     */
    effectivePrice?: number;
    onSale?: boolean;
    discountPercentage?: number;
    currency?: string;
    inStock?: boolean;
    category?: CategoryRef;
    primaryImage?: ImageRef;
}

