/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicSettingsResponse { 
    'store.name'?: string;
    'store.tagline'?: string;
    'store.logo_image_id'?: string | null;
    /**
     * E.164 sin \'+\' ni espacios.
     */
    'whatsapp.phone_number'?: string;
    'whatsapp.template_single'?: string;
    'whatsapp.template_multi_header'?: string;
    'whatsapp.template_multi_item'?: string;
    'whatsapp.template_multi_footer'?: string;
    'catalog.page_size'?: number;
    'catalog.hide_out_of_stock'?: boolean;
    'catalog.max_selection'?: number;
    'seo.default_og_image_id'?: string | null;
}

