/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicEventRequest { 
    type: PublicEventRequestTypeEnum;
    productId?: string | null;
    /**
     * JSON libre, tope de 2000 caracteres serializados.
     */
    payload?: { [key: string]: any | null; } | null;
    sessionId: string;
    payloadWithinLimit?: boolean;
}
export enum PublicEventRequestTypeEnum {
    ProductView = 'PRODUCT_VIEW',
    WhatsappClick = 'WHATSAPP_CLICK',
    Search = 'SEARCH',
    CategoryView = 'CATEGORY_VIEW'
};



