/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshResponse { 
    /**
     * Nuevo JWT de acceso, válido 15 minutos.
     */
    accessToken?: string;
    accessTokenExpiresAt?: string;
}

