/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleResponse { 
    id?: string;
    name?: string;
    description?: string;
    /**
     * Un rol de sistema no se puede renombrar.
     */
    system?: boolean;
    permissions?: Set<string>;
    createdAt?: string;
    updatedAt?: string;
}

