/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingAdminResponse { 
    key?: string;
    type?: string;
    /**
     * Si es visible en `GET /api/public/v1/settings`.
     */
    isPublic?: boolean;
    value?: string;
    updatedAt?: string;
}

