/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SettingsUpdateRequest { 
    /**
     * null = no se toca.
     */
    storeName?: string;
    /**
     * null = no se toca.
     */
    storeTagline?: string;
    /**
     * null = no se toca.
     */
    storeLogoImageId?: string;
    /**
     * E.164 sin \'+\' ni espacios. null = no se toca.
     */
    whatsappPhoneNumber?: string;
    /**
     * Rechaza cualquier marcador fuera del catálogo cerrado de 14. null = no se toca.
     */
    whatsappTemplateSingle?: string;
    whatsappTemplateMultiHeader?: string;
    whatsappTemplateMultiItem?: string;
    whatsappTemplateMultiFooter?: string;
    /**
     * null = no se toca.
     */
    catalogPageSize?: number;
    /**
     * null = no se toca.
     */
    catalogHideOutOfStock?: boolean;
    /**
     * null = no se toca.
     */
    catalogMaxSelection?: number;
    /**
     * null = no se toca.
     */
    seoDefaultOgImageId?: string;
    /**
     * null = no se toca.
     */
    analyticsEnabled?: boolean;
}

