/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TypeCount { 
    type?: TypeCountTypeEnum;
    count?: number;
}
export enum TypeCountTypeEnum {
    ProductView = 'PRODUCT_VIEW',
    WhatsappClick = 'WHATSAPP_CLICK',
    Search = 'SEARCH',
    CategoryView = 'CATEGORY_VIEW'
};



