/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRoleRequest { 
    /**
     * Los roles de sistema no se pueden renombrar.
     */
    name: string;
    description?: string;
    /**
     * No puede incluir un código que quien edita el rol no posea.
     */
    permissionCodes?: Set<string>;
}

