/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequest { 
    fullName: string;
    /**
     * Pasar a false revoca todos los tokens de refresco del usuario.
     */
    enabled?: boolean;
}

