/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleSummary } from './role-summary';


export interface UserResponse { 
    id?: string;
    email?: string;
    fullName?: string;
    enabled?: boolean;
    mustChangePassword?: boolean;
    roles?: Set<RoleSummary>;
    lastLoginAt?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

