/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhatsAppPreviewResponse { 
    /**
     * Renderizado con datos de ejemplo de un solo producto.
     */
    single?: string;
    /**
     * Renderizado con datos de ejemplo de varios productos.
     */
    multi?: string;
}

