/**
 * shop-backend-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhatsAppPreviewRequest { 
    /**
     * Rechaza cualquier marcador fuera del catálogo cerrado de 14.
     */
    templateSingle: string;
    templateMultiHeader: string;
    templateMultiItem: string;
    templateMultiFooter: string;
}

